### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by petersopko** [petersopko/kodabot-test#23]

**Comment by kodaDev2839** [comment]
okay

**Comment by kodaDev2839** [comment]
I will take this

**Comment by petersopko** [comment]
ASSIGNED - @kodaDev2839 🔒 Locked period -> 24 hours until Monday, March 21st 2022, 08:45:56 UTC

**Comment by petersopko** [comment]
I will take this

**Comment by petersopko** [comment]
ASSIGNED - @petersopko 🔒 Locked period -> 24 hours until Monday, March 21st 2022, 08:47:34 UTC

**Comment by kodaDev2839** [comment]
i take this

**Comment by petersopko** [comment]
ASSIGNED - @kodaDev2839 🔒 Locked period -> 24 hours until Monday, March 21st 2022, 08:49:11 UTC
